version: "3"
services:

  static:
    image: static
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    container_name: ${PROJECT_NAME:-my-plugin}-static
    ports:
      - "${LOCALHOST_HTTP_PORT:-80}:80"
      - "${LOCALHOST_HTTPS_PORT:-443}:443"
    volumes:
      - ./.html:/usr/share/nginx/html
      - ../:/usr/share/nginx/html/plugins/${PROJECT_NAME:-my-plugin}
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    command: /wait-for-it.sh -t 600 php:9000 -- nginx -g 'daemon off;'
    env_file: ../.env

  php:
    image: php:${PHP_VERSION:-7.2}
    build:
      context: ./
      dockerfile: php/Dockerfile
      args:
        php_version: ${PHP_VERSION:-7.2}
        xdebug_remote_autostart: ${XDEBUG_REMOTE_AUTOSTART:-1}
        xdebug_remote_enable: ${XDEBUG_REMOTE_ENABLE:-1}
        xdebug_remote_host: ${XDEBUG_REMOTE_HOST:-192.168.65.1}
        xdebug_remote_port: ${XDEBUG_REMOTE_PORT:-9000}
    container_name: ${PROJECT_NAME:-my-plugin}-php-${PHP_VERSION:-7.2}
    ports:
      - "${LOCALHOST_PHP_PORT:-9001}:9000"
    volumes:
      - ./.html:/var/www/html
      - ../:/var/www/html/plugins/${PROJECT_NAME:-my-plugin}
    depends_on:
      - mysql
    environment:
      WP_VERSION: ${WP_VERSION:-latest}
      WC_VERSION: ${WC_VERSION:-latest}
      WP_MULTISITE: ${WP_MULTISITE:-0}
      WP_CLI_PACKAGES_DIR: ${WP_CLI_PACKAGES_DIR:-/var/www/html}
      WP_USER: ${WP_USER:-admin}
      WP_EMAIL: ${WP_EMAIL:-example@example.com}
      WP_PASSWORD: ${WP_PASSWORD:-password}
      WP_TITLE: ${WP_TITLE:-Localhost}
      WP_URL: ${WP_URL:-localhost}
      DB_HOST: ${DB_HOST:-mysql:3306}
      DB_NAME: ${DB_NAME:-wordpress}
      DB_PASSWORD: ${DB_PASSWORD:-wordpress}
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    env_file: ../.env

  mysql:
    image: mysql:${MYSQL_VERSION:-8.0}
    container_name: ${PROJECT_NAME:-my-plugin}-mysql-${MYSQL_VERSION:-8.0}
    ports:
      - "${LOCALHOST_MYSQL_PORT:-3306}:3306"
    volumes:
      - ./.db/mysql${MYSQL_VERSION:-8.0}:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
    env_file: ../.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME:-my-plugin}-phpmyadmin
    links:
      - mysql:db
    ports:
      - "8092:80"
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wordpress}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-wordpress}
      MYSQL_USER: ${DB_NAME:-wordpress}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wordpress}
      PMA_HOST: mysql

  mailhog:
    image: mailhog/mailhog
    container_name: ${PROJECT_NAME:-my-plugin}-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

networks:
  default:
