version: '2'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../.html:/usr/share/nginx/html
      - ../:/usr/share/nginx/html/wp-content/plugins/${PROJECT_NAME}
    depends_on:
      - php54
      - php55
      - php56
      - php70
    expose:
      - "80"
      - "443"
    networks:
      default:
        aliases:
          - php54.local
          - php55.local
          - php56.local
          - php70.local

  php54:
    build: ./php54
    container_name: php54
    restart: always
    ports:
      - "9054:9000"
    volumes:
      - ../.html:/var/www/html
      - ../:/var/www/html/wp-content/plugins/${PROJECT_NAME}
    depends_on:
      - mysql56
      - mysql57
    extra_hosts:
      - "remote_host:${XDEBUG_REMOTE_HOST}"
    networks:
      - default
    env_file: wordpress.env

  php55:
    build: ./php55
    container_name: php55
    restart: always
    ports:
      - "9055:9000"
    volumes:
      - ../.html:/var/www/html
      - ../:/var/www/html/wp-content/plugins/${PROJECT_NAME}
    depends_on:
      - mysql56
      - mysql57
    extra_hosts:
      - "remote_host:${XDEBUG_REMOTE_HOST}"
    networks:
      - default
    env_file: wordpress.env

  php56:
    build: ./php56
    container_name: php56
    restart: always
    ports:
      - "9056:9000"
    volumes:
      - ../.html:/var/www/html
      - ../:/var/www/html/wp-content/plugins/${PROJECT_NAME}
    depends_on:
      - mysql56
      - mysql57
    extra_hosts:
      - "remote_host:${XDEBUG_REMOTE_HOST}"
    networks:
      - default
    env_file: wordpress.env

  php70:
    build: ./php70
    container_name: php70
    restart: always
    ports:
      - "9070:9000"
    volumes:
      - ../.html:/var/www/html
      - ../:/var/www/html/wp-content/plugins/${PROJECT_NAME}
    depends_on:
      - mysql56
      - mysql57
    extra_hosts:
      - "remote_host:${XDEBUG_REMOTE_HOST}"
    networks:
      - default
    env_file: wordpress.env

  mysql56:
    build: ./mysql56
    container_name: mysql56
    restart: always
    ports:
      - "9016:3306"
    volumes:
      - ../.data/mysql56:/var/lib/mysql
    networks:
      - default
    env_file: mysql.env

  mysql57:
    build: ./mysql57
    container_name: mysql57
    restart: always
    ports:
      - "9017:3306"
    volumes:
      - ../.data/mysql57:/var/lib/mysql
    networks:
      - default
    env_file: mysql.env

networks:
  default: