version: '2'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../.html:/usr/share/nginx/html
      - ../:/usr/share/nginx/html/latest/wp-content/plugins/woocommerce-pos
    links:
      - php54
      - php55
      - php56
      - php70
    depends_on:
      - php54
      - php55
      - php56
      - php70

  php54:
    build: ./php54
    container_name: php54
    ports:
      - "9054:9000"
    volumes:
      - ../.html:/var/www/html
      - ../:/var/www/html/latest/wp-content/plugins/woocommerce-pos
    links:
      - mysql56
      - mysql57
    depends_on:
      - mysql56
      - mysql57

  php55:
    build: ./php55
    container_name: php55
    ports:
      - "9055:9000"
    volumes:
      - ../.html:/var/www/html
      - ../:/var/www/html/latest/wp-content/plugins/woocommerce-pos
    links:
      - mysql56
      - mysql57
    depends_on:
      - mysql56
      - mysql57

  php56:
    build: ./php56
    container_name: php56
    restart: always
    ports:
      - "9056:9000"
    volumes:
      - ../.html:/var/www/html
      - ../:/var/www/html/latest/wp-content/plugins/woocommerce-pos
    links:
      - mysql56
      - mysql57
    depends_on:
      - mysql56
      - mysql57
    environment:
      WORDPRESS_DB_HOST: mysql57:3306
      WORDPRESS_DB_PASSWORD: wordpress

  php70:
    build: ./php70
    container_name: php70
    ports:
      - "9070:9000"
    volumes:
      - ../.html:/var/www/html
      - ../:/var/www/html/latest/wp-content/plugins/woocommerce-pos
    links:
      - mysql56
      - mysql57
    depends_on:
      - mysql56
      - mysql57

  mysql56:
    build: ./mysql56
    container_name: mysql56
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "9016:3306"
    volumes:
      - ../.data/mysql56:/var/lib/mysql

  mysql57:
    build: ./mysql57
    container_name: mysql57
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "9017:3306"
    volumes:
      - ../.data/mysql57:/var/lib/mysql