version: '2.1'
services:
  static:
    build: ./nginx
    container_name: ${PROJECT_NAME}-static
    restart: always
    ports:
      - "${LOCALHOST_HTTP_PORT:-80}:80"
      - "${LOCALHOST_HTTPS_PORT:-443}:443"
    volumes:
      - ../.html:/usr/share/nginx/html
      - ../:/usr/share/nginx/html/wp-content/plugins/${PROJECT_NAME}
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/includes:/etc/nginx/conf.d/includes
    depends_on:
      - app-php56
    expose:
      - "80"
      - "443"
    networks:
      - default
    env_file: ../.env

  app-php54:
    build: ./php54
    container_name: ${PROJECT_NAME}-app-php54
    restart: always
    ports:
      - "${LOCALHOST_PHP56_PORT:-9054}:9000"
    volumes:
      - ../.html:/var/www/html
      - ../:/var/www/html/wp-content/plugins/${PROJECT_NAME}
    depends_on:
      db-mysql56:
        condition: service_healthy
    extra_hosts:
      - "remote_host:${XDEBUG_REMOTE_HOST}"
    networks:
      - default
    env_file:
      - wordpress.env
      - ../.env
    environment:
      WORDPRESS_DB_HOST: "${PROJECT_NAME}-db-mysql54:3306"

  db-mysql56:
    build: ./mysql56
    container_name: ${PROJECT_NAME}-db-mysql56
    restart: always
    ports:
      - "${LOCALHOST_MYSQL54_PORT:-9016}:3306"
    volumes:
      - ../.data/mysql56:/var/lib/mysql
    networks:
      - default
    env_file: mysql.env
    healthcheck:
      test: [
        "CMD-SHELL",
        "mysql --protocol=socket -hlocalhost -uroot -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'",
      ]
      interval: 2s
      timeout: 10s
      retries: 20

networks:
  default: