version: '2'
services:
  nginx:
    build:
      context: ./nginx
      args:
        PHP_VERSION: php54
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../.html:/usr/share/nginx/html
      - ../:/usr/share/nginx/html/wp-content/plugins/${PROJECT_NAME}
    links:
      - php54
    depends_on:
      - php54
    env_file: ../.env

  php54:
    build: ./php54
    container_name: php54
    restart: always
    ports:
      - "9054:9000"
    volumes:
      - ../.html:/var/www/html
      - ../:/var/www/html/wp-content/plugins/${PROJECT_NAME}
    links:
      - mysql57
    depends_on:
      - mysql57
    env_file:
      - wordpress.env
      - ../.env

  mysql57:
    build: ./mysql57
    container_name: mysql57
    restart: always
    ports:
      - "9017:3306"
    volumes:
      - ../.data/mysql57:/var/lib/mysql
    env_file: mysql.env